version: "3.3"

services:
  nextjs:
    ports:
      - 3200:3200
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env